### PR TITLE
Allow puppetlabs/stdlib 6.x / rspec: Use stdlib master branch instead of 4.1.0

### PR DESCRIPTION
**Pull request by bastelfreak**

### CODE REVIEW

**Comment by bastelfreak** [comment]
@raphink if you by any chance can merge and release this, it would be awesome <3

**Comment by bastelfreak** [comment]
https://github.com/hercules-team/augeasproviders/pull/165 should probably merged before this one

**Comment by mat1010** [comment]
Since #165 is already meged, could this PR for `stdlib < 7.0.0`  be merged as well?

**Comment by bastelfreak** [comment]
I'm going to close this PR and handle it in a new PR

**Pull request closed without merging**
